"""initial schema: all 21 tables + the hotel_best_price view (from the ERD)

Revision ID: 0001
Revises:
Create Date: 2026-10-06 02:45:10.924870
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

HOTEL_BEST_PRICE_SQL = """
CREATE OR REPLACE VIEW hotel_best_price AS
SELECT h.id AS hotel_id,
       h.city_id,
       h.name AS hotel_name,
       h.stars,
       best.price_per_night AS min_price,
       counts.offers_count,
       best.company_id AS best_company_id
FROM hotels h
JOIN (
    SELECT hotel_id, COUNT(*)::int AS offers_count
    FROM offers WHERE status = 'active' GROUP BY hotel_id
) counts ON counts.hotel_id = h.id
JOIN LATERAL (
    SELECT o.price_per_night, o.company_id
    FROM offers o
    WHERE o.hotel_id = h.id AND o.status = 'active'
    ORDER BY o.price_per_night ASC
    LIMIT 1
) best ON TRUE;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "interests",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("icon", sa.String(length=60), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Enum("traveler", "company", "admin", name="user_role"), nullable=False),
        sa.Column("language", sa.String(length=8), server_default="en", nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "companies",
        sa.Column("owner_user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("license_no", sa.String(length=80), nullable=True),
        sa.Column("license_doc_url", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("facebook_url", sa.Text(), nullable=True),
        sa.Column("instagram_url", sa.Text(), nullable=True),
        sa.Column("google_rating", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.Column("years_active", sa.Integer(), nullable=True),
        sa.Column("initial_score", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.Column("trust_score", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.Column("reviews_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "suspended", name="company_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.BigInteger(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_owner_user_id"), "companies", ["owner_user_id"], unique=False)
    op.create_table(
        "hotels",
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amenities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hotels_city_id"), "hotels", ["city_id"], unique=False)
    op.create_table(
        "nl_queries",
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("generated_sql", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum("ok", "failed", "flagged", name="nl_query_status"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("fixed_sql", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nl_queries_user_id"), "nl_queries", ["user_id"], unique=False)
    op.create_table(
        "places",
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "type", sa.Enum("monument", "museum", "activity", "food", "nature", name="place_type"), nullable=False
        ),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("verified_info", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("era", sa.String(length=80), nullable=True),
        sa.Column("opening_hours", sa.String(length=120), nullable=True),
        sa.Column("ticket_price", sa.Integer(), nullable=True),
        sa.Column("visit_minutes", sa.Integer(), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("recognition_label", sa.String(length=80), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recognition_label"),
    )
    op.create_index(op.f("ix_places_city_id"), "places", ["city_id"], unique=False)
    op.create_table(
        "trips",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("budget_level", sa.Enum("low", "mid", "high", name="budget_level"), nullable=False),
        sa.Column("budget_total", sa.Integer(), nullable=True),
        sa.Column("suggest_destinations", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.Enum("draft", "saved", name="trip_status"), server_default="draft", nullable=False),
        sa.Column("share_token", sa.String(length=64), nullable=True),
        sa.Column("total_cost", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("share_token"),
    )
    op.create_index(op.f("ix_trips_user_id"), "trips", ["user_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("trip_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Enum("user", "assistant", name="message_role"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_trip_id"), "chat_messages", ["trip_id"], unique=False)
    op.create_table(
        "offers",
        sa.Column("hotel_id", sa.BigInteger(), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("room_type", sa.String(length=60), nullable=False),
        sa.Column("price_per_night", sa.Integer(), nullable=False),
        sa.Column("breakfast_included", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("free_cancellation", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("cancellation_days", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "paused", "expired", "flagged", name="offer_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hotel_id", "company_id", "room_type", name="uq_offer_per_room_type"),
    )
    op.create_index(op.f("ix_offers_company_id"), "offers", ["company_id"], unique=False)
    op.create_index(op.f("ix_offers_hotel_id"), "offers", ["hotel_id"], unique=False)
    op.create_table(
        "place_images",
        sa.Column("place_id", sa.BigInteger(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("source", sa.Enum("admin", "user_scan", name="image_source"), nullable=False),
        sa.Column("used_for_training", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["place_id"], ["places.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_place_images_place_id"), "place_images", ["place_id"], unique=False)
    op.create_table(
        "place_interests",
        sa.Column("place_id", sa.BigInteger(), nullable=False),
        sa.Column("interest_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["interest_id"], ["interests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["place_id"], ["places.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("place_id", "interest_id"),
    )
    op.create_table(
        "reviews",
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("trip_id", sa.BigInteger(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("sentiment", sa.Enum("positive", "neutral", "negative", name="review_sentiment"), nullable=True),
        sa.Column("sentiment_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_review_rating"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "trip_id", "company_id", name="uq_review_once_per_trip"),
    )
    op.create_index(op.f("ix_reviews_company_id"), "reviews", ["company_id"], unique=False)
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    op.create_table(
        "scans",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("place_id", sa.BigInteger(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["place_id"], ["places.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scans_user_id"), "scans", ["user_id"], unique=False)
    op.create_table(
        "training_examples",
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        sa.Column("source_query_id", sa.BigInteger(), nullable=True),
        sa.Column("added_by", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["source_query_id"], ["nl_queries.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trip_cities",
        sa.Column("trip_id", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trip_id", "city_id"),
    )
    op.create_table(
        "trip_interests",
        sa.Column("trip_id", sa.BigInteger(), nullable=False),
        sa.Column("interest_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interests.id"],
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trip_id", "interest_id"),
    )
    op.create_table(
        "price_alerts",
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("offer_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.Enum("undercut", "price_anomaly", name="alert_type"), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["offer_id"], ["offers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_alerts_company_id"), "price_alerts", ["company_id"], unique=False)
    op.create_table(
        "trip_changes",
        sa.Column("trip_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("cost_delta", sa.Integer(), server_default="0", nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("proposed", "kept", "undone", name="change_status"),
            server_default="proposed",
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["chat_messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_changes_trip_id"), "trip_changes", ["trip_id"], unique=False)
    op.create_table(
        "trip_days",
        sa.Column("trip_id", sa.BigInteger(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column("offer_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.ForeignKeyConstraint(["offer_id"], ["offers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "day_number", name="uq_trip_day_number"),
    )
    op.create_index(op.f("ix_trip_days_trip_id"), "trip_days", ["trip_id"], unique=False)
    op.create_table(
        "trip_items",
        sa.Column("trip_day_id", sa.BigInteger(), nullable=False),
        sa.Column("place_id", sa.BigInteger(), nullable=True),
        sa.Column("type", sa.Enum("visit", "meal", "transport", "free_time", name="trip_item_type"), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("cost", sa.Integer(), server_default="0", nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["place_id"], ["places.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trip_day_id"], ["trip_days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_items_trip_day_id"), "trip_items", ["trip_day_id"], unique=False)
    # ### end Alembic commands ###

    # View read by NL-to-SQL (Person 5) and the market position logic (Person 6).
    op.execute(HOTEL_BEST_PRICE_SQL)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS hotel_best_price")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_items_trip_day_id"), table_name="trip_items")
    op.drop_table("trip_items")
    op.drop_index(op.f("ix_trip_days_trip_id"), table_name="trip_days")
    op.drop_table("trip_days")
    op.drop_index(op.f("ix_trip_changes_trip_id"), table_name="trip_changes")
    op.drop_table("trip_changes")
    op.drop_index(op.f("ix_price_alerts_company_id"), table_name="price_alerts")
    op.drop_table("price_alerts")
    op.drop_table("trip_interests")
    op.drop_table("trip_cities")
    op.drop_table("training_examples")
    op.drop_index(op.f("ix_scans_user_id"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_company_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_table("place_interests")
    op.drop_index(op.f("ix_place_images_place_id"), table_name="place_images")
    op.drop_table("place_images")
    op.drop_index(op.f("ix_offers_hotel_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_company_id"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_chat_messages_trip_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_trips_user_id"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_places_city_id"), table_name="places")
    op.drop_table("places")
    op.drop_index(op.f("ix_nl_queries_user_id"), table_name="nl_queries")
    op.drop_table("nl_queries")
    op.drop_index(op.f("ix_hotels_city_id"), table_name="hotels")
    op.drop_table("hotels")
    op.drop_index(op.f("ix_companies_owner_user_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("interests")
    op.drop_table("cities")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP TYPE IF EXISTS company_status")
    op.execute("DROP TYPE IF EXISTS review_sentiment")
    op.execute("DROP TYPE IF EXISTS budget_level")
    op.execute("DROP TYPE IF EXISTS trip_status")
    op.execute("DROP TYPE IF EXISTS trip_item_type")
    op.execute("DROP TYPE IF EXISTS message_role")
    op.execute("DROP TYPE IF EXISTS change_status")
    op.execute("DROP TYPE IF EXISTS place_type")
    op.execute("DROP TYPE IF EXISTS image_source")
    op.execute("DROP TYPE IF EXISTS nl_query_status")
    op.execute("DROP TYPE IF EXISTS offer_status")
    op.execute("DROP TYPE IF EXISTS alert_type")
